name: Generate Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: karrad1201
          svg_out_path: snake.svg
          filters: '{"days": 365}'
          
      - name: Commit to output branch
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          add: snake.svg
          message: "Update snake animation"
          author_name: GitHub Actions
          author_email: actions@github.com
