name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: Platane/snk@master
        with:
          github_user_name: karrad1201
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_other_contributions: true
          output: snake.svg
          
      - uses: EndBug/add-and-commit@v9
        with:
          branch: output
          add: snake.svg
          message: "Update snake"
          token: ${{ secrets.GITHUB_TOKEN }}
