name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Запускать ежедневно в полночь
  workflow_dispatch: # Разрешить ручной запуск

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v2
        id: snake
        with:
          github_user_name: karrad1201
          svg_out_path: dist/github-contribution-grid-snake.svg
          filters: '{"days": 365}' # За последний год
          
      - name: Push to output branch
        if: steps.snake.outputs.snake_created == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/
          
      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          branch: output
          path: dist
          message: "Update snake animation"
