name: Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
          fetch-depth: 0

      - uses: Platane/snk@master
        with:
          github_user_name: karrad1201
          svg_out_path: snake.svg

      - uses: EndBug/add-and-commit@v9
        with:
          add: snake.svg
          message: "Update snake [skip ci]"
