name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v2
        with:
          github_user_name: karrad1201
          svg_out_path: dist/github-contribution-grid-snake.svg
      - uses: EndBug/add-and-commit@v9
        with:
          branch: output
          path: dist
          message: "Update snake"
