name: Snake Generator

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: output
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: karrad1201
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_other_contributions: true
          force_update: true
          output: snake.svg

      - name: Force Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add snake.svg
          git commit -m "Update snake: $(date)"
          git push origin output --force
